[package]
name = "rex-ucph"
version = "0.1.0"
authors = ["Valdemar Erk <valdemar@erk.io>"]
description = "This is a library for the ARLO robots in use in the REX course at UCPH"
repository = "https://github.com/Erk-/rex-rust"
license = "ISC"

[dependencies]
serialport = "^3.0.0"
